Scripts in bin: improved script quality, option listing and exit status on -help

diff --git a/bin/foamNewApp b/bin/foamNewApp
--- a/bin/foamNewApp
+++ b/bin/foamNewApp
@@ -30,47 +30,53 @@
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
-DIR="$FOAM_ETC/codeTemplates/app"
+dir="$FOAM_ETC/codeTemplates/app"
 
 usage() {
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
-Usage: $Script [-h | -help] <applicationName>
+Usage: $Script [OPTIONS] <application>
+options:
+  -help  | -h         help
 
-* Create directory with source and compilation files for a new application
-  <applicationName> (dir)
-  - <applicationName>.C
+Create directory with source and compilation files for a new application
+  <application> (dir)
+  - <application>.C
   - Make (dir)
     - files
     - options
-  Compiles an executable named <applicationName> in \$FOAM_USER_APPBIN:
+  Compiles an executable named <application> in \$FOAM_USER_APPBIN:
   $FOAM_USER_APPBIN
 USAGE
+}
+
+error() {
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    usage
     exit 1
 }
 
 case "$1" in
-(-h | -help)
-    usage
+(-help | -h)
+    usage && exit 0
     ;;
 -*)
-    usage "$1 is not a valid filename"
+    error "$1 is not a valid filename"
     ;;
 esac
 
-[ "$#" -eq 1 ] || usage "Wrong number of arguments"
-[ -d "$1" ] && usage "$1 directory already exists, aborting..."
+[ "$#" -eq 1 ] || error "Wrong number of arguments"
+[ -d "$1" ] && error "$1 directory already exists, aborting..."
 
-NAME=$1
-YEAR=$(date +%Y)
+app=$1
+year=$(date +%Y)
 
-echo "Creating application code directory $NAME" && mkdir $NAME
-sed -e "s#NAME#${NAME}#g" \
-    -e "s#YEAR#${YEAR}#g" \
-    ${DIR}/app.C > $NAME/$NAME.C
+echo "Creating application code directory ${app}" && mkdir "${app}"
+sed -e "s#NAME#${app}#g" \
+    -e "s#YEAR#${year}#g" \
+    "${dir}/app.C" > "${app}/${app}.C"
 
-echo "Creating Make subdirectory" && mkdir $NAME/Make
-sed "s#NAME#${NAME}#g" ${DIR}/Make/files > $NAME/Make/files
-cp ${DIR}/Make/options $NAME/Make
+echo "Creating Make subdirectory" && mkdir "${app}/Make"
+sed "s#NAME#${app}#g" "${dir}/Make/files" > "${app}/Make/files"
+cp "${dir}/Make/options" "${app}/Make"
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamNewFunctionObject b/bin/foamNewFunctionObject
--- a/bin/foamNewFunctionObject
+++ b/bin/foamNewFunctionObject
@@ -31,54 +31,64 @@
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
-DIR="$FOAM_ETC/codeTemplates/functionObject"
+dir="$FOAM_ETC/codeTemplates/functionObject"
+
+error() {
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    usage
+    exit 1
+}
 
 usage() {
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
-    cat<<USAGE
-Usage: $Script [-h | -help] <functionObjectName>
+        cat<<USAGE
+Usage: $Script [OPTIONS] <functionObject>
+options:
+  -help  | -h         help
 
-* Create directory with source and compilation files for a new function object
-  <functionObjectName> (dir)
-  - <functionObjectName>.H
-  - <functionObjectName>.C
-  - IO<functionObjectName>.H
+Create directory with source and compilation files for a new function object
+  <functionObject> (dir)
+  - <functionObject>.H
+  - <functionObject>.C
+  - IO<functionObject>.H
   - Make (dir)
     - files
     - options
-  Compiles a library named lib<functionObjectName>FunctionObject.so in
+  Compiles a library named lib<functionObject>FunctionObject.so in
   \$FOAM_USER_LIBBIN:
   $FOAM_USER_LIBBIN
 USAGE
-    exit 1
 }
 
 case "$1" in
 (-h | -help)
-    usage
+    usage && exit 0
     ;;
 -*)
-    usage "$1 is not a valid option/filename"
+    error "$1 is not a valid option/filename"
     ;;
 esac
 
-[ "$#" -eq 1 ] || usage "Wrong number of arguments"
-[ -d "$1" ] && usage "$1 directory already exists, aborting..."
+[ "$#" -eq 1 ] || error "Wrong number of arguments"
+[ -d "$1" ] && error "$1 directory already exists, aborting..."
 
-NAME=$1
-YEAR=$(date +%Y)
+func=$1
+year=$(date +%Y)
 
-echo "Creating function object code directory $NAME" && mkdir $NAME
-for F in $(ls ${DIR}/*.*)
+echo "Creating function object code directory $func" && mkdir "${func}"
+
+tmp=$(mktemp tmp.XXXXXX)
+find "${dir}" -name '*.*' > "$tmp"
+while IFS= read -r template_file
 do
-    FILE=$(basename $F | sed "s#FUNCTIONOBJECT#${NAME}#g")
-    sed -e "s#FUNCTIONOBJECT#${NAME}#g" \
-        -e "s#YEAR#${YEAR}#g" \
-        ${F} > ${NAME}/${FILE}
-done
+    file=$(basename "$template_file" | sed "s#FUNCTIONOBJECT#${func}#g")
+    sed -e "s#FUNCTIONOBJECT#${func}#g" \
+        -e "s#YEAR#${year}#g" \
+        "$template_file" > "${func}/${file}"
+done < "$tmp"
+rm "$tmp"
 
-echo "Creating Make subdirectory" && mkdir $NAME/Make
-sed "s#FUNCTIONOBJECT#${NAME}#g" ${DIR}/Make/files > $NAME/Make/files
-cp ${DIR}/Make/options $NAME/Make
+echo "Creating Make subdirectory" && mkdir "$func/Make"
+sed "s#FUNCTIONOBJECT#${func}#g" "${dir}/Make/files" > "$func/Make/files"
+cp "${dir}/Make/options" "$func/Make"
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamSequenceVTKFiles b/bin/foamSequenceVTKFiles
--- a/bin/foamSequenceVTKFiles
+++ b/bin/foamSequenceVTKFiles
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2015 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2015-2017 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
 # License
@@ -33,54 +33,58 @@
 #     - Default directory name for VTK files is postProcessing
 #
 #------------------------------------------------------------------------------
-usage () {
+error() {
     exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
-    cat <<USAGE
+    usage
+    exit 1
+}
+
+usage() {
+        cat <<USAGE
 
 Usage: ${0##*/} [OPTIONS] ...
 options:
-  -c | -case <dir>    specify case directory (default = local dir)
-  -d | -dir <dir>     post-processing directory <dir> (default = postProcessing)
-  -h | -help          help
-  -o | -out <dir>     output links directory <dir> (default = sequencedVTK)
+options:
+  -case | -c <dir>    specify case directory (default = local dir)
+  -dir  | -d <dir>    post-processing directory <dir> (default = postProcessing)
+  -help | -h          help
+  -out  | -o <dir>    output links directory <dir> (default = sequencedVTK)
 
 Creates symbolic links to all VTK files in a post-processing directory
 Links form a sequence like name.0000.vtk, name.0001.vtk, etc.
 Paraview recognises the link names as a sequence which can be opened and played.
 The sequence of links to images can be used to create a video from the images.
 - Default directory name for VTK files is postProcessing
-
 USAGE
-    exit 1
 }
 
-DIR=postProcessing
-OUT=sequencedVTK
+dir=postProcessing
+out=sequencedVTK
 
 while [ "$#" -gt 0 ]
 do
    case "$1" in
    -c | -case)
-      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-      cd "$2" 2>/dev/null || usage "directory does not exist:  '$2'"
+      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
+      cd "$2" 2>/dev/null || error "directory does not exist:  '$2'"
       shift 2
       ;;
    -d | -dir)
-      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-      DIR=$2
+      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
+      dir=$2
       shift 2
       ;;
    -h | -help)
-      usage
+      usage && exit 0
       ;;
    -o | -out)
-      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-      OUT=$2
+      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
+      out=$2
       shift 2
       ;;
    -*)
-      usage "invalid option '$1'"
+      error "invalid option '$1'"
       ;;
    *)
       break
@@ -88,39 +92,36 @@ do
     esac
 done
 
-if [ ! -d $DIR ]; then
-    echo "Cannot find postProcessing directory, exiting."
-    exit 0
-fi
+[ ! -d "$dir" ] && error "Cannot find postProcessing directory, exiting."
 
-FILES=$(find $DIR -type f -name *vtk)
-NAMES=$(for f in $FILES; do basename $f .vtk; done | sort -u)
+files=$(find "$dir" -type f -name "*vtk")
+names=$(for f in $files; do basename "$f" .vtk; done | sort -u)
 
-if [ -d $OUT ]; then
-    echo "$OUT directory already exists.  Deleting links within it..."
-    rm -rf $OUT/*
+if [ -d "$out" ]; then
+    echo "$out directory already exists.  Deleting links within it..."
+    rm "${out:?}"/* 2>/dev/null
 else
-    echo "Creating $OUT directory..."
-    mkdir $OUT
+    echo "Creating $out directory..."
+    mkdir "$out"
 fi
 
-for N in $NAMES
+for n in $names
 do
-    echo "Sequencing all VTK files named $N.vtk"
+    echo "Sequencing all VTK files named $n.vtk"
 
     # Create list of VTK files, ordered by time step
-    FILE_LIST=$(echo $FILES | \
+    file_list=$(echo "$files" | \
         tr " " "\n" | \
-        grep $N.vtk | \
+        grep "$n.vtk" | \
         awk -F'/' '{print($(NF-1)" "$0)}' | \
         sort -k 1 -g | \
         cut -d' ' -f2)
 
     i=0
-    for F in $FILE_LIST
+    for f in $file_list
     do
-        i=$(expr $i + 1) # Relies on ordered list of $sourceFiles
-        LINK=$(printf "${N}.%04d.vtk" $i)
-        ln -s ../$F $OUT/$LINK
+        i=$(( i + 1 )) # Relies on ordered list of files
+        link=$(printf "${n}.%04d.vtk" $i)
+        ln -s "../$f" "$out/$link"
     done
 done
