Scripts in bin: improved script quality, option listing and exit status on -help

diff --git a/bin/foamCreateVideo b/bin/foamCreateVideo
--- a/bin/foamCreateVideo
+++ b/bin/foamCreateVideo
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2015-2016 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2015-2017 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
 # License
@@ -32,19 +32,17 @@
 #------------------------------------------------------------------------------
 
 usage () {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat <<USAGE
 
 Usage: ${0##*/} [OPTIONS] ...
 options:
-  -d | -dir <dir>     directory containing png images (default local dir)
-  -f | -fps <fps>     frames per second (default = 10)
-  -h | -help          help
-  -i | -image <name>  name of image sequence (default = image)
-  -o | -out <name>    name of output video file (default = video)
-  -s | -start <frame> specify the start frame number for avconv
-  -w | -webm          WebM output video file format
+  -dir   | -d <dir>   directory containing png images (default local dir)
+  -fps   | -f <fps>   frames per second (default = 10)
+  -help  | -h         help
+  -image | -i <name>  name of image sequence (default = image)
+  -out   | -o <name>  name of output video file (default = video)
+  -start | -s <frame> specify the start frame number for avconv
+  -webm  | -w         WebM output video file format
 
 Creates a video file from a sequence of PNG images
 - A sequence named "image" will expect files image.0000.png, image.0001.png, etc
@@ -55,56 +53,55 @@ Creates a video file from a sequence of PNG images
 Requires avconv or mencoder for MPEG-4 output, avconv for WebM output
 
 USAGE
+}
+
+error () {
+    exec 1>&2
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    usage
     exit 1
 }
 
-
 # Default settings
-DIR='.'
-IMAGE='image'
-VIDEO='video'
-FPS=10
-FMT='mp4'
-START_NUMBER=''
+dir=.
+image=image
+video=video
+fps=10
+fmt=mp4
 
 while [ "$#" -gt 0 ]
 do
    case "$1" in
    -h | -help)
-      usage
+      usage && exit 0
       ;;
-   -d | -directory)
-      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-      DIR=$2
+   -d | -dir)
+      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
+      dir=$2
       shift 2
       ;;
    -f | -fps)
-      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-      FPS=$2
+      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
+      fps=$2
       shift 2
       ;;
    -i | -image)
-      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-      IMAGE=$2
+      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
+      image=$2
       shift 2
       ;;
    -o | -out)
-      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-      VIDEO=$2
-      shift 2
-      ;;
-   -s | -start)
-      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-      START_NUMBER="-start_number $2"
+      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
+      video=$2
       shift 2
       ;;
    -w | -webm)
-      FMT=webm
-      echo "Selected $FMT format, requires avconv..."
+      fmt=webm
+      echo "Selected $fmt format, requires avconv..."
       shift
       ;;
    -*)
-      usage "invalid option '$1'"
+      error "invalid option '$1'"
       ;;
    *)
       break
@@ -116,37 +113,36 @@ done
 # MAIN
 #
 
-[ -f "$(ls -1 $DIR/$IMAGE.*.png | head -1)" ] || usage "Cannot find first file in image sequence"
+[ -f "$(find "$dir" -name "$image.*.png" | sort | head -1)" ] || \
+    error "Cannot find first file in image sequence"
 
-if [ "$FMT" = "webm" ] ; then
+if [ "$fmt" = "webm" ] ; then
     if command -v avconv >/dev/null 2>&1 ; then
         echo "Creating image with avconv..."
         avconv \
-            -framerate $FPS \
-            $START_NUMBER \
-            -i ${DIR}/${IMAGE}.%04d.png \
+            -framerate "$fps" \
+            -i "${dir}/${image}.%04d.png" \
             -c:v libvpx -crf 15 -b:v 1M \
-            $VIDEO.$FMT
+            "$video.$fmt"
     else
-        usage "Please install avconv"
+        error "Please install avconv"
     fi
 else
-    if command -v avconv >/dev/null 2>&1 ; then
+    if ! command -v avconv >/dev/null 2>&1 ; then
         echo "Creating image with avconv..."
         avconv \
-            -framerate $FPS \
-            $START_NUMBER \
-            -i ${DIR}/${IMAGE}.%04d.png \
+            -framerate "$fps" \
+            -i "${dir}/${image}.%04d.png" \
             -c:v libx264 -pix_fmt yuv420p \
-            $VIDEO.$FMT
+            "$video.$fmt"
     elif command -v mencoder >/dev/null 2>&1 ; then
         echo "Creating image with mencoder..."
         mencoder \
-            "mf://$DIR/$IMAGE.*.png" \
-            -mf fps=$FPS \
-            -o $VIDEO.$FMT \
+            "mf://$dir/$image.*.png" \
+            -mf fps="$fps" \
+            -o "$video.$fmt" \
             -ovc x264
     else
-        usage "Please install avconv or mencoder"
+        error "Please install avconv or mencoder"
     fi
 fi
diff --git a/bin/foamJob b/bin/foamJob
--- a/bin/foamJob
+++ b/bin/foamJob
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2011-2015 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2011-2017 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
 # License
@@ -31,8 +31,6 @@
 #
 #------------------------------------------------------------------------------
 usage() {
-    exec 1>&2
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
 
 Usage: ${0##*/} [OPTION] <application> ...
@@ -49,6 +47,12 @@ options:
   Redirects the output to 'log' in the case directory
 
 USAGE
+}
+
+error () {
+    exec 1>&2
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    usage
     exit 1
 }
 
@@ -58,14 +62,14 @@ echoArgs() {
 
     for stringItem in "$@"; do
 
-        echo -n "${addSpace}"
+        printf "%s" "${addSpace}"
 
         if [ "${stringItem##* }" = "$stringItem" ]
         then
-            echo -n "$stringItem"
+            printf "%s" "$stringItem"
             addSpace=" "
         else
-            echo -n "'$stringItem'"
+            printf "%s" "'$stringItem'"
             addSpace=" "
         fi
 
@@ -76,37 +80,10 @@ echoArgs() {
 
 unset version
 
-# Replacement for possibly buggy 'which'
 findExec() {
-    case "$1" in
-    */*)
-        if [ -x "$1" ]
-        then
-            echo "$1"
-            return 0
-        fi
-        ;;
-    esac
-
-    oldIFS=$IFS
-    IFS=':'
-    for d in $PATH
-    do
-        # echo "testing: $d/$1" 1>&2
-        if [ -x "$d/$1" -a ! -d "$d/$1" ]
-        then
-            # echo "Found exec: $d/$1" 1>&2
-            IFS=$oldIFS
-            echo "$d/$1"
-            return 0
-        fi
-     done
-     IFS=$oldIFS
-     echo ""
-     return 1
+    which "$1" 2>/dev/null
+    command -v "$1" >/dev/null 2>&1
 }
-
-
 
 # Main script
 #~~~~~~~~~~~~
@@ -118,11 +95,11 @@ while [ "$#" -gt 0 ]
 do
    case "$1" in
    -h | -help)
-      usage
+      usage && exit 0
       ;;
    -case)
-      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
-      cd "$2" 2>/dev/null || usage "directory does not exist:  '$2'"
+      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
+      cd "$2" 2>/dev/null || error "directory does not exist:  '$2'"
       shift 2
       ;;
    -p | -parallel)
@@ -142,7 +119,7 @@ do
       shift
       ;;
    -v | -version)
-      [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
+      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
       version="$2"
       shift 2
       ;;
@@ -151,7 +128,7 @@ do
       break
       ;;
    -*)
-      usage "invalid option '$1'"
+      error "invalid option '$1'"
       ;;
    *)
       break
@@ -159,7 +136,7 @@ do
    esac
 done
 
-[ "$#" -ge 1 ] || usage "No application specified"
+[ "$#" -ge 1 ] || error "No application specified"
 
 
 # Use foamExec for a specified version
@@ -169,11 +146,11 @@ then
     # When possible, determine if application even exists
     if [ -z "$version" ]
     then
-        findExec $1 >/dev/null || usage "Application '$1' not found"
+        findExec "$1" >/dev/null || error "Application '$1' not found"
     fi
 
     # Use foamExec for dispatching
-    APPLICATION=`findExec foamExec` || usage "'foamExec' not found"
+    APPLICATION=$(findExec foamExec) || error "'foamExec' not found"
 
     [ -n "$version" ] && APPLICATION="$APPLICATION -version $version"
 
@@ -184,7 +161,7 @@ then
     fi
 
 else
-    APPLICATION=`findExec $1` || usage "Application '$1' not found"
+    APPLICATION=$(findExec "$1") || error "Application '$1' not found"
     echo "Application : $1"
     shift
 fi
@@ -200,7 +177,7 @@ then
     #
     if [ -r "processor0" ]
     then
-        NPROCS="`/bin/ls -1d processor* | wc -l`"
+        NPROCS="$(/bin/ls -1d processor* | wc -l)"
     else
         echo "Case is not currently decomposed"
         if [ -r system/decomposeParDict ]
@@ -218,7 +195,7 @@ then
     #
     # Find mpirun
     #
-    mpirun=`findExec mpirun` || usage "'mpirun' not found"
+    mpirun=$(findExec mpirun) || error "'mpirun' not found"
     mpiopts="-np $NPROCS"
 
     #
diff --git a/bin/foamNewBC b/bin/foamNewBC
--- a/bin/foamNewBC
+++ b/bin/foamNewBC
@@ -30,12 +30,13 @@
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
-DIR="$FOAM_ETC/codeTemplates/BC"
+dir="$FOAM_ETC/codeTemplates/BC"
 
 usage() {
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
-Usage: $Script [-h | -help] <base> <type> <boundaryConditionName>
+Usage: $Script [OPTIONS] <base> <type> <boundaryConditionName>
+options:
+  -help  | -h         help
 
 * Create directory of source and compilation files for a new boundary condition
   <boundaryConditionName> (dir)
@@ -62,8 +63,14 @@ USAGE
     exit 1
 }
 
+error() {
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    usage
+    exit 1
+}
+
 cap() {
-    echo $1 | sed -e 's/^./\U&/'
+    echo "$1" | sed -e 's/^./\U&/'
 }
 
 # Implicitly covers a lone -help
@@ -71,105 +78,107 @@ cap() {
 
 case "$1" in
 (-h | -help)
-    usage
+    usage && exit 0
     ;;
 (-f | -fixedValue | fixedValue)
-    BASE=fixedValue
+    base=fixedValue
     ;;
 (-m | -mixed | mixed )
-    BASE=mixed
+    base=mixed
     ;;
 (*)
-    usage "Unknown <base> condition '$1'"
+    error "Unknown <base> condition '$1'"
     ;;
 esac
 shift
 
 case "$1" in
 (-a | -all | all | template)
-    TYPE=Type
-    UNIT='VALUE-or-(VALUE 0 0)'
+    type=Type
+    unit='VALUE-or-(VALUE 0 0)'
     ;;
 (-s | -scalar | scalar)
-    TYPE=scalar
-    UNIT=VALUE
+    type=scalar
+    unit=VALUE
     ;;
 (-v | -vector | vector)
-    TYPE=vector
-    UNIT='(VALUE 0 0)'
+    type=vector
+    unit='(VALUE 0 0)'
     ;;
 (-t | -tensor | tensor)
-    TYPE=tensor
-    UNIT='(VALUE 0 0 0 0 0 0 0 0)'
+    type=tensor
+    unit='(VALUE 0 0 0 0 0 0 0 0)'
     ;;
 (-symmTensor | symmTensor)
-    TYPE=symmTensor
-    UNIT='(VALUE 0 0 0 0 0)'
+    type=symmTensor
+    unit='(VALUE 0 0 0 0 0)'
     ;;
 (-sphericalTensor | sphericalTensor)
-    TYPE=sphericalTensor
-    UNIT=VALUE
+    type=sphericalTensor
+    unit=VALUE
     ;;
 (*)
-    usage "Unknown <type> option '$1'"
+    error "Unknown <type> option '$1'"
     ;;
 esac
 shift
-[ "$#" -eq 1 ] || usage "Wrong number of arguments"
-NAME=$1
+[ "$#" -eq 1 ] || error "Wrong number of arguments"
+name=$1
 
 # Prevents over-writing of existing directory
-[ -d $NAME ] && usage "$NAME directory already exists, aborting..."
-echo "Creating $NAME directory" && mkdir $NAME
+[ -d "$name" ] && error "$name directory already exists, aborting..."
+echo "Creating $name directory" && mkdir "$name"
 
 # Establish meta template files to copy
-FILES=$(cd ${DIR} && ls *.*)
-[ "$TYPE" = "Type" ] || FILES=$(cd ${DIR} && ls BC.[CH])
+files=$(find "${dir}" -name "*.*" -type f -exec basename {} \;)
+[ "$type" = "Type" ] || \
+    files=$(find "${dir}" -name "BC.[CH]" -type f -exec basename {} \;)
 
 # Substitutions for meta-template files
-FIELD="Field<${TYPE}>"
-[ "$TYPE" = "Type" ] || FIELD=${TYPE}Field
+field="Field<${type}>"
+[ "$type" = "Type" ] || field=${type}Field
 
-FVPATCHF=fvPatch$(cap $FIELD)
-CLASS=$NAME$(cap $FVPATCHF)
-PARENT=$BASE$(cap $FVPATCHF)
-CONSTRUCT=$(echo $CLASS | sed 's/<Type>//g')
-YEAR=$(date +%Y)
+fvpatchf=fvPatch$(cap $field)
+class=$name$(cap "$fvpatchf")
+parent=$base$(cap "$fvpatchf")
+construct=$(echo "$class" | sed 's/<Type>//g')
+year=$(date +%Y)
 
 # Create some example values for the Description
 n=0
-for N in $(echo "ZERO ONE TWO THREE FOUR")
+for N in zero one two three four
 do
-   eval $(expr $N='$(echo $UNIT | sed "s#VALUE#$n#g")')
-   n=$(( $n + 1 ))
+    eval $N="$(echo \"$unit\" | sed "s#VALUE#$n#g")"
+    n=$(( n + 1 ))
 done
 
 # Make substitutions to meta-template files
-for F in $FILES
+for f in $files
 do
-    EXT=$(echo $F | sed "s#BC##")
-    NEWFILE=${CONSTRUCT}${EXT}
-    echo "   Adding file ${NEWFILE}..."
+    ext=$(echo "$f" | sed "s#BC##")
+    new_file=${construct}${ext}
+    echo "   Adding file ${new_file}..."
 
-    # Adds readScalar function when TYPE = scalar
-    sed -e "s#TYPE#${TYPE}#g" \
-        -e "s#NAME#${NAME}#g" \
-        -e "s#BASE#${BASE}#g" \
-        -e "s#CONSTRUCT#${CONSTRUCT}#g" \
-        -e "s#YEAR#${YEAR}#g" \
-        -e "s#CLASS#${CLASS}#g" \
-        -e "s#FIELD#${FIELD}#g" \
-        -e "s#FVPATCHF#${FVPATCHF}#g" \
-        -e "s#PARENT#${PARENT}#g" \
-        -e "s#ZERO#${ZERO}#g" \
-        -e "s#ONE#${ONE}#g" \
-        -e "s#TWO#${TWO}#g" \
-        -e "s#THREE#${THREE}#g" \
-        -e "s#FOUR#${FOUR}#g" \
+    # Adds readScalar function when type = scalar
+    # shellcheck disable=SC2154
+    sed -e "s#TYPE#${type}#g" \
+        -e "s#NAME#${name}#g" \
+        -e "s#BASE#${base}#g" \
+        -e "s#CONSTRUCT#${construct}#g" \
+        -e "s#YEAR#${year}#g" \
+        -e "s#CLASS#${class}#g" \
+        -e "s#FIELD#${field}#g" \
+        -e "s#FVPATCHF#${fvpatchf}#g" \
+        -e "s#PARENT#${parent}#g" \
+        -e "s#ZERO#${zero}#g" \
+        -e "s#ONE#${one}#g" \
+        -e "s#TWO#${two}#g" \
+        -e "s#THREE#${three}#g" \
+        -e "s#FOUR#${four}#g" \
         -e 's/>>/>>/g' \
-        ${DIR}/${F} > ${NAME}/${NEWFILE}
+        "${dir}/${f}" > "${name}/${new_file}"
 
-    case $BASE in
+    case $base in
         fixedValue)
             # refValue(), refGrad(), valueFraction() removed
             # phip removed
@@ -178,7 +187,7 @@ do
                 -e '/refGrad/d' \
                 -e '/valueFraction/d' \
                 -e '/const scalarField\& phip/,/);/d' \
-                ${NAME}/${NEWFILE}
+                "${name}/${new_file}"
             ;;
         mixed)
             # evaluate() removed
@@ -186,15 +195,15 @@ do
             sed -i \
                 -e '/evaluate/d' \
                 -e 's/operator==/refValue() =/g' \
-                ${NAME}/${NEWFILE}
+                "${name}/${new_file}"
             ;;
     esac
 
-    case $TYPE in
+    case $type in
         Type)
             # Build Macro removed (in ..Fields.C)
             sed -i -e '/Build Macro/,/^}/d' \
-                ${NAME}/${NEWFILE}
+                "${name}/${new_file}"
             ;;
         *)
             # template<class Type> removed
@@ -206,13 +215,15 @@ do
                 -e 's/this->//g' \
                 -e 's/\.template[\t ]*\([a-Z]\)/\.\1/g' \
                 -e '/#ifdef NoRepository/,/\/\/ */d' \
-                ${NAME}/${NEWFILE}
+                "${name}/${new_file}"
             ;;
     esac
 done
 
-echo "Creating Make subdirectory" && cp -r ${DIR}/Make ${NAME}
-COMPILED=$(cd ${NAME} && ls -r1 *C | head -1) # ...Fields.C for template class
-sed -i -e "s#NAME#${NAME}#g" -e "s#COMPILED.*#${COMPILED}#g" ${NAME}/Make/files
+echo "Creating Make subdirectory" && cp -r "${dir}/Make" "${name}"
+
+# Get ...Fields.C for template class, otherwise ...Field.C
+compiled=$(find "${name}" -name "*.C" -exec basename {} \; | sort | tail -1)
+sed -i -e "s#NAME#${name}#g" -e "s#COMPILED.*#${compiled}#g" "${name}/Make/files"
 
 #------------------------------------------------------------------------------
