etc: Explicit control of decomposition and ParaView installation type
*** Note that this commit depends on a corresponding change in
ThirdParty-dev. Ensure that both repositories are up to date before
re-building OpenFOAM.

New environment variables have been added to explicitly control the
installation type of the thirdparty decomposition libraries and of the
ParaView visualiation software. These are set in the etc/bashrc and can
be overridden in a ~/.OpenFOAM/<version>/prefs.sh file or similar.

The variables relating to the decomposition libraries are SCOTCH_TYPE,
METIS_TYPE, PARMETIS_TYPE and ZOLTAN_TYPE, and they can take values of
none, system, or ThirdParty. In the case of ThirdParty, a
<library>_VERSION variable can also be specified. If the version is not
specified then the configuration will search for a source directory, and
if multiple such directories are found then the one with the highest
version number will be used.

The variable relating to ParaView is ParaView_TYPE, and this can be
similarly be set to none, system, or ThirdParty, and ParaView_VERSION
can also be specified when the type is ThirdParty. If the version is not
specified then the installation with the highest version number will be
used.

An example  ~/.OpenFOAM/dev/prefs.sh file, in which all decomposition
libraries are enabled, and the Scotch and ParaView versions are
explicitly set, is as follows:

    export SCOTCH_TYPE=ThirdParty
    export SCOTCH_VERSION=7.0.3
    export METIS_TYPE=ThirdParty
    export PARMETIS_TYPE=ThirdParty
    export ZOLTAN_TYPE=ThirdParty

    export ParaView_TYPE=ThirdParty
    export ParaView_VERSION=5.11.2

*** Note that if version numbers are not set then the configuration will
search for a decomposition source directory, but it will search for a
ParaView installation directory. This is because decomposition libraries
are built as part of OpenFOAM's ./Allwmake, but ParaView is not. This
distinction remains. If a local compilation of ParaView is needed, then
'./makeParaView -version X.XX.X' should be called explicitly in the
third party directory prior to building OpenFOAM.

The name of the third party directory can now also be independently set.
This simplifies some packaging processes in that it permits third party
to be located within the OpenFOAM installation directory and therefore
bundled into the same binary package.

diff --git a/bin/foamEtcFile b/bin/foamEtcFile
--- a/bin/foamEtcFile
+++ b/bin/foamEtcFile
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     | Website:  https://openfoam.org
-#   \\  /    A nd           | Copyright (C) 2011-2022 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2011-2024 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # License
@@ -99,44 +99,33 @@ prefixDir="${projectDir%/*}"
 # the name used for the project directory
 projectDirName="${projectDir##*/}"
 
-# version number used for debian packaging
-unset versionNum
-
-#
-# handle standard and debian naming convention
-#
+# handle standard and packaged naming conventions
 case "$projectDirName" in
-    OpenFOAM-*)     # standard naming convention OpenFOAM-<VERSION>
-        version="${projectDirName##OpenFOAM-}"
-        ;;
-    openfoam[0-9]*) # debian naming convention
-        versionNum="${projectDirName##openfoam}"
-        case "$versionNum" in
-        [4-9]) # v4-9
-            version="$versionNum"
+        OpenFOAM-*) # standard naming convention OpenFOAM-<VERSION>
+            version="${projectDirName##OpenFOAM-}"
             ;;
-        [1-2][0-9]) # v10 onwards
-            version="$versionNum"
+        openfoam-dev) # debian naming convention for dev
+            version="${projectDirName##openfoam-}"
             ;;
-        3[0-9]) # e.g. v3.0
-            version=$(echo "$versionNum" | sed -e 's@\(.\)\(.\)@\1.\2@')
+        openfoam[1-2][0-9]) # debian naming convention for v10 onwards
+            version="${projectDirName##openfoam}"
             ;;
-        [1-2][0-9][0-9]) # e.g. v1.7.0
-            version=$(echo "$versionNum" | sed -e 's@\(.\)\(.\)\(.\)@\1.\2.\3@')
+        openfoam[4-9]) # debian naming convention for v4-9
+            version="${projectDirName##openfoam}"
+            ;;
+        openfoam3[0-9]) # debian naming convention for v3.?
+            version=$(echo "${projectDirName##openfoam}" | sed -e 's@\(.\)\(.\)@\1.\2@')
+            ;;
+        openfoam[1-2][0-9][0-9]) # debian naming convention for v1.?.? and v2.?.?
+            version=$(echo "${projectDirName##openfoam}" | sed -e 's@\(.\)\(.\)\(.\)@\1.\2.\3@')
+            ;;
+        app) # flatpak naming convention
+            version="${FLATPAK_ID##OpenFOAM-}"
             ;;
         *)
-            version="$WM_PROJECT_VERSION"
+            echo "Error : unknown/unsupported naming convention"
+            exit 1
             ;;
-        esac
-        ;;
-    openfoam-dev) # debian naming convention
-        versionNum="${projectDirName##openfoam}"
-        version="${versionNum##-}"
-        ;;
-    *)
-        echo "Error : unknown/unsupported naming convention"
-        exit 1
-        ;;
 esac
 
 # default mode is 'ugo'
@@ -184,11 +173,6 @@ do
     -v | -version)
         [ "$#" -ge 2 ] || error "'$1' option requires an argument"
         version="$2"
-        # convert x.y.z -> xyz version (if installation looked like debian)
-        if [ -n "$versionNum" ]
-        then
-            versionNum=$(echo "$version" | sed -e 's@\.@@g')
-        fi
         shift
         ;;
     --)
@@ -204,15 +188,6 @@ do
     esac
     shift
 done
-
-
-# debugging:
-# echo "Installed locations:"
-# for i in projectDir prefixDir projectDirName version versionNum
-# do
-#     eval echo "$i=\$$i"
-# done
-
 
 # Save the essential bits of information
 # silently remove leading ~OpenFOAM/ (used in Foam::findEtcFile)
@@ -237,14 +212,7 @@ esac
 
 case "$mode" in
 *o*)  # other (shipped)
-    if [ -n "$versionNum" ]
-    then
-        # debian packaging
-        dirList="$dirList $prefixDir/openfoam$versionNum/etc"
-    else
-        # standard packaging
-        dirList="$dirList $prefixDir/${WM_PROJECT:-OpenFOAM}-$version/etc"
-    fi
+    dirList="$dirList $prefixDir/$projectDirName/etc"
     ;;
 esac
 set -- $dirList
diff --git a/bin/paraFoam b/bin/paraFoam
--- a/bin/paraFoam
+++ b/bin/paraFoam
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     | Website:  https://openfoam.org
-#   \\  /    A nd           | Copyright (C) 2011-2022 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2011-2024 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # License
@@ -28,9 +28,6 @@
 # Description
 #     start paraview with the OpenFOAM libraries
 #
-# Note
-#     combining -block or -builtin options with the -region option yields
-#     undefined behaviour
 #------------------------------------------------------------------------------
 usage() {
     cat<<USAGE
@@ -61,19 +58,12 @@ error() {
 }
 
 pvExec () {
-    if [ "$ParaView_GL" = mesa ]
-    then
-        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ParaView_LIB_DIR/mesa paraview "$@"
-    else
-        paraview "$@"
-    fi
+    # For now filter out any ld.so errors. Caused by non-system compiler?
+    paraview "$@" 2>&1 | grep -v -F 'Inconsistency detected by ld.so'
 }
 
-noPVReader () {
+noPV() {
     cat<<EOF
-FATAL ERROR: The official reader module for OpenFOAM data does not exist on
-your system.  This means that the version of ParaView you are using was not
-compiled with OpenFOAM, or distributed with a packaged version of OpenFOAM.
 
 For information on packaged versions of OpenFOAM/ParaView and compilation of
 OpenFOAM/ParaView, see https://openfoam.org/download
@@ -83,6 +73,25 @@ module provided with ParaView by running:
     paraFoam -builtin
 
 EOF
+}
+
+noPVExe () {
+    cat<<EOF
+FATAL ERROR: A ParaView executable was not found on your system.  This means
+that ParaView is not installed, or that OpenFOAM has been configured to use a
+different installation of ParaView from that which is installed.
+EOF
+noPV
+}
+
+noPVReader () {
+    cat<<EOF
+FATAL ERROR: The reader module for OpenFOAM data was not found on your system.
+This means that OpenFOAM was not built with ParaView support, or that ParaView
+is not installed, or that OpenFOAM has been configured to use a different
+installation of ParaView from that which is installed.
+EOF
+noPV
 }
 
 # We want to do nice exit when running paraview to give paraview opportunity
@@ -99,7 +108,8 @@ export LC_ALL=C
 # Reader extension
 extension=OpenFOAM
 
-requirePV=1
+requirePVExe=1
+requirePVReader=1
 
 # Parse options
 while [ "$#" -gt 0 ]
@@ -114,7 +124,8 @@ do
         ;;
     -builtin)
         extension=foam
-        requirePV=0
+        requirePVExe=1
+        requirePVReader=0
         shift
         ;;
     -case)
@@ -133,12 +144,14 @@ do
         ;;
     -touch)
         optTouch=true
-        requirePV=0
+        requirePVExe=0
+        requirePVReader=0
         shift
         ;;
     -touchAll)
         optTouch=all
-        requirePV=0
+        requirePVExe=0
+        requirePVReader=0
         shift
         ;;
     --)
@@ -154,8 +167,26 @@ do
     esac
 done
 
-# Check that reader module has been built
-[ $requirePV -eq 1 ] && \
+# Check for incompatibility of options
+if [ -n "$regionName" ]
+then
+    case $extension in
+    blockMesh)
+        echo "FATAL ERROR: The builtin reader does not support blockMesh"
+        exit 1
+        ;;
+    foam)
+        echo "FATAL ERROR: The builtin reader does not support regions"
+        exit 1
+        ;;
+    esac
+fi
+
+# Check that the executable and/or the reader module are available
+[ $requirePVExe -eq 1 ] && \
+    ! which paraview > /dev/null 2>&1 && \
+    noPVExe && exit 1
+[ $requirePVReader -eq 1 ] && \
     ! [ -f "$PV_PLUGIN_PATH/libPVFoamReader_SM.so" ] && \
     noPVReader && exit 1
 
@@ -174,14 +205,11 @@ hasDataArg()
         shift
     done
 }
-
 hasDataArg "$@"
 
-# Get a sensible caseName from the directory name
+# Construct a case name from the directory name
 caseName=${PWD##*/}
 caseFile="$caseName.$extension"
-fvControls="system"
-
 if [ -n "$regionName" ]
 then
     if [ ! -d constant/"$regionName" ]
@@ -190,37 +218,41 @@ then
         exit 1
     else
         caseFile="$caseName{$regionName}.$extension"
-        fvControls="$fvControls/$regionName"
     fi
 fi
 
+# If the touch option is set, then create files and exit
 case "${optTouch:-false}" in
 all)
-    extension=OpenFOAM
+    # Block mesh
     if [ -f system/blockMeshDict ] || [ -f constant/polyMesh/blockMeshDict ]
     then
         touch "$caseName.blockMesh"
         echo "Created '$caseName.blockMesh'"
     fi
-    touch "$caseName.$extension"
-    echo "Created '$caseName.$extension'"
-    # Discover probable regions
+
+    # Default region
+    touch "$caseName.OpenFOAM"
+    echo "Created '$caseName.OpenFOAM'"
+
+    # Find other probable regions
     for region in constant/*
     do
-        [ -d "$region" ] && [ -d "${region}/polyMesh" ] && \
+        [ -d "$region/polyMesh" ] && \
             regionName=${region##*/} && \
-            touch "$caseName{$regionName}.$extension" && \
-            echo "Created '$caseName{$regionName}.$extension'"
+            touch "$caseName{$regionName}.OpenFOAM" && \
+            echo "Created '$caseName{$regionName}.OpenFOAM'"
     done
     exit 0
     ;;
+
 true)
+    # Default region
     touch "$caseFile"
     echo "Created '$caseFile'"
     exit 0
     ;;
 esac
-
 
 # Parent directory for normal or parallel results
 case "$caseName" in
@@ -228,72 +260,64 @@ case "$caseName" in
     *)          parentDir="."  ;;
 esac
 
-
+# If we have a --data=... argument, then send this directly to paraview
 if [ "${hasData:-false}" = true ]
 then
-
-    # Has --data=.., send directly to paraview
     pvExec "$@"
-
-else
-
-    # Check existence of essential files
-    warn="WARN file does not exist:"
-    case $extension in
-        blockMesh)
-            blockMeshDictDir=system/blockMeshDict
-            if [ -f constant/polyMesh/blockMeshDict ]
-            then
-                blockMeshDictDir=constant/polyMesh/blockMeshDict
-            fi
-            for check in \
-                system/controlDict \
-                    $blockMeshDictDir \
-                ;
-            do
-                [ -s "$parentDir/$check" ] || [ -s "$parentDir/$check.orig" ] ||
-                {
-                    [ -n "$warn" ] && echo "$warn" 1>&2
-                    echo "    $parentDir/$check" 1>&2
-                    unset warn
-                }
-            done
-            ;;
-
-        builtin | OpenFOAM)
-            for check in \
-                system/controlDict \
-                ;
-            do
-                [ -s "$parentDir/$check" ] || [ -s "$parentDir/$check.orig" ] ||
-                {
-                    [ -n "$warn" ] && echo "$warn" 1>&2
-                    echo "    $parentDir/$check" 1>&2
-                    unset warn
-                }
-            done
-            ;;
-    esac
-
-    [ -n "$warn" ] || {
-        echo "Cannot locate OpenFOAM-format case files"
-        printf "Would you like to open ParaView anyway <Y|n>:"
-        read open
-        [ "$open" = "" ] || echo "$open" | grep -iqE "^y" && pvExec
-        exit
-    }
-
-    # Only create/remove caseFile if it didn't already exist
-    [ -e "$caseFile" ] || {
-        trap "rm -f $caseFile 2>/dev/null; exit 0" EXIT TERM INT
-        touch "$caseFile"
-        echo "Created temporary '$caseFile'"
-    }
-
-    # For now filter out any ld.so errors. Caused by non-system compiler?
-    pvExec --data="$caseFile" "$@" 2>&1 \
-        | grep -v -F 'Inconsistency detected by ld.so'
+    exit 0
 fi
 
+# Check existence of essential files
+warn="WARN file does not exist:"
+case $extension in
+    blockMesh)
+        blockMeshDictDir=system/blockMeshDict
+        if [ -f constant/polyMesh/blockMeshDict ]
+        then
+            blockMeshDictDir=constant/polyMesh/blockMeshDict
+        fi
+
+        for check in system/controlDict $blockMeshDictDir
+        do
+            [ -s "$parentDir/$check" ] || [ -s "$parentDir/$check.orig" ] ||
+            {
+                [ -n "$warn" ] && echo "$warn" 1>&2
+                echo "    $parentDir/$check" 1>&2
+                unset warn
+            }
+        done
+        ;;
+
+    OpenFOAM | foam)
+        for check in system/controlDict
+        do
+            [ -s "$parentDir/$check" ] || [ -s "$parentDir/$check.orig" ] ||
+            {
+                [ -n "$warn" ] && echo "$warn" 1>&2
+                echo "    $parentDir/$check" 1>&2
+                unset warn
+            }
+        done
+        ;;
+esac
+
+# Warn if essential files do not exist
+[ -n "$warn" ] || {
+    echo "Cannot locate OpenFOAM-format case files"
+    printf "Would you like to open ParaView anyway <Y|n>:"
+    read open
+    [ "$open" = "" ] || echo "$open" | grep -iqE "^y" && pvExec
+    exit
+}
+
+# Only create/remove the caseFile if it didn't already exist
+[ -e "$caseFile" ] || {
+    trap "rm -f $caseFile 2>/dev/null; exit 0" EXIT TERM INT
+    touch "$caseFile"
+    echo "Created temporary '$caseFile'"
+}
+
+# Run paraview
+pvExec --data="$caseFile" "$@"
 
 #------------------------------------------------------------------------------
diff --git a/etc/config.sh/settings b/etc/config.sh/settings
--- a/etc/config.sh/settings
+++ b/etc/config.sh/settings
@@ -2,7 +2,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     | Website:  https://openfoam.org
-#   \\  /    A nd           | Copyright (C) 2011-2023 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2011-2024 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # License
@@ -33,20 +33,21 @@
 # Set environment variables according to system type
 export WM_ARCH=`uname -s`
 
+# Define compilation flags for the system type
 case "$WM_ARCH" in
 Linux)
     WM_ARCH=linux
 
     # Compiler specifics
     case `uname -m` in
-        i686)
-            export WM_ARCH_OPTION=32
-            export WM_CC='gcc'
-            export WM_CXX='g++'
-            export WM_CFLAGS='-fPIC'
-            export WM_CXXFLAGS='-fPIC -std=c++0x'
-            export WM_LDFLAGS=
-        ;;
+    i686)
+        export WM_ARCH_OPTION=32
+        export WM_CC='gcc'
+        export WM_CXX='g++'
+        export WM_CFLAGS='-fPIC'
+        export WM_CXXFLAGS='-fPIC -std=c++0x'
+        export WM_LDFLAGS=
+    ;;
 
     x86_64)
         case "$WM_ARCH_OPTION" in
@@ -58,6 +59,7 @@ Linux)
             export WM_CXXFLAGS='-m32 -fPIC -std=c++0x'
             export WM_LDFLAGS='-m32'
             ;;
+
         64)
             WM_ARCH=linux64
             export WM_COMPILER_LIB_ARCH=64
@@ -67,10 +69,11 @@ Linux)
             export WM_CXXFLAGS='-m64 -fPIC -std=c++0x'
             export WM_LDFLAGS='-m64'
             ;;
+
         *)
-            echo "Unknown WM_ARCH_OPTION '$WM_ARCH_OPTION', should be 32 or 64"\
-                 1>&2
+            echo "Unknown WM_ARCH_OPTION '$WM_ARCH_OPTION', should be 32 or 64" 1>&2
             ;;
+
         esac
         ;;
 
@@ -132,7 +135,7 @@ SunOS)
     export WM_LDFLAGS='-mabi=64 -G0'
     ;;
 
-*)    # An unsupported operating system
+*)       # An unsupported operating system
     /bin/cat <<USAGE 1>&2
 
     Your "$WM_ARCH" operating system is not supported by this release
@@ -220,8 +223,10 @@ unset MPFR_ARCH_PATH GMP_ARCH_PATH
 if [ -z "$WM_COMPILER_TYPE" ]
 then
     WM_COMPILER_TYPE=system
-    echo "Warning in $WM_PROJECT_DIR/etc/config.sh/settings:" 1>&2
-    echo "    WM_COMPILER_TYPE not set, using '$WM_COMPILER_TYPE'" 1>&2
+    /bin/cat <<USAGE 1>&2
+Warning in $WM_PROJECT_DIR/etc/config.sh/settings:
+    WM_COMPILER_TYPE not set, using '$WM_COMPILER_TYPE'
+USAGE
 fi
 
 # Load configured compiler versions, regardless of the compiler type
@@ -236,18 +241,23 @@ OpenFOAM | ThirdParty)
         gccDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$gcc_version
         gmpDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$gmp_version
         mpfrDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$mpfr_version
-        mpcDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$mpc_version
+        if [ -n "$mpc_version" ]
+        then
+            mpcDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$mpc_version
+        fi
 
         # Check that the compiler directory can be found
-        [ -d "$gccDir" ] || {
-            echo 1>&2
-            echo "Warning in $WM_PROJECT_DIR/etc/config.sh/settings:" 1>&2
-            echo "    Cannot find $gccDir installation." 1>&2
-            echo "    Please install this compiler version or if you wish to" \
-                 " use the system compiler," 1>&2
-            echo "    change the 'WM_COMPILER_TYPE' setting to 'system'" 1>&2
-            echo
-        }
+        if [ ! -d "$gccDir" ]
+        then
+            /bin/cat <<USAGE 1>&2
+
+Warning in $WM_PROJECT_DIR/etc/config.sh/settings:
+    Cannot find $gccDir installation.
+    Please install this compiler version or if you wish to use the system compiler,
+    change the 'WM_COMPILER_TYPE' setting to 'system'
+
+USAGE
+        fi
 
         _foamAddMan     $gccDir/man
         _foamAddPath    $gccDir/bin
@@ -266,35 +276,45 @@ OpenFOAM | ThirdParty)
         fi
     fi
     unset gcc_version gccDir
-    unset gmp_version gmpDir  mpfr_version mpfrDir  mpc_version mpcDir
+    unset gmp_version gmpDir mpfr_version mpfrDir mpc_version mpcDir
 
     if [ -n "$clang_version" ]
     then
         clangDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER_ARCH/$clang_version
 
         # Check that the compiler directory can be found
-        [ -d "$clangDir" ] || {
-            echo 1>&2
-            echo "Warning in $WM_PROJECT_DIR/etc/config.sh/settings:" 1>&2
-            echo "    Cannot find $clangDir installation." 1>&2
-            echo "    Please install this compiler version or if you wish to" \
-                 " use the system compiler," 1>&2
-            echo "    change the 'WM_COMPILER_TYPE' setting to 'system'" 1>&2
-            echo 1>&2
-        }
+        if [ ! -d "$clangDir" ]
+        then
+            /bin/cat <<USAGE 1>&2
+
+Warning in $WM_PROJECT_DIR/etc/config.sh/settings:
+    Cannot find $clangDir installation.
+    Please install this compiler version or if you wish to use the system compiler,
+    change the 'WM_COMPILER_TYPE' setting to 'system'
+
+USAGE
+        fi
 
         _foamAddMan     $clangDir/share/man
         _foamAddPath    $clangDir/bin
     fi
     unset clang_version clangDir
     ;;
+
 system)
     # Use system compiler
     ;;
+
 *)
-    echo "Warn: WM_COMPILER_TYPE='$WM_COMPILER_TYPE' is unsupported" 1>&2
-    echo "   treating as 'system' instead" 1>&2
+    /bin/cat <<USAGE 1>&2
+Warn: WM_COMPILER_TYPE='$WM_COMPILER_TYPE' is unsupported
+   treating as 'system' instead
+USAGE
     ;;
 esac
+
+# Cleanup environment:
+# ~~~~~~~~~~~~~~~~~~~~
+unset WM_COMPILER_TYPE
 
 #------------------------------------------------------------------------------
