New version of wmake supporting out-of-tree object and dependency files

diff --git a/applications/Allwmake b/applications/Allwmake
--- a/applications/Allwmake
+++ b/applications/Allwmake
@@ -1,22 +1,27 @@
 #!/bin/sh
-cd ${0%/*} || exit 1    # run from this directory
+cd ${0%/*} || exit 1    # Run from this directory
+
+# Parse arguments for library compilation
+targetType=libso
+. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
 
 wmakeCheckPwd "$WM_PROJECT_DIR/applications" || {
-    echo "Error: Current directory is not \$WM_PROJECT_DIR/applications"
+    echo "Allwmake error: Current directory is not \$WM_PROJECT_DIR/applications"
     echo "    The environment variables are inconsistent with the installation."
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
 }
 
 [ -n "$FOAM_EXT_LIBBIN" ] || {
-    echo "Error: FOAM_EXT_LIBBIN not set"
+    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
 }
 
 set -x
 
-wmake all utilities $*
-wmake all solvers $*
+wmake -all utilities $*
+wmake -all solvers $*
+
 
 # ----------------------------------------------------------------- end-of-file
diff --git a/src/Allwmake b/src/Allwmake
--- a/src/Allwmake
+++ b/src/Allwmake
@@ -1,86 +1,83 @@
 #!/bin/sh
-cd ${0%/*} || exit 1    # run from this directory
-makeType=${1:-libso}
+cd ${0%/*} || exit 1    # Run from this directory
+
+# Parse arguments for library compilation
+targetType=libso
+. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
 
 wmakeCheckPwd "$WM_PROJECT_DIR/src" || {
-    echo "Error: Current directory is not \$WM_PROJECT_DIR/src"
+    echo "Allwmake error: Current directory is not \$WM_PROJECT_DIR/src"
     echo "    The environment variables are inconsistent with the installation."
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
 }
 
 [ -n "$FOAM_EXT_LIBBIN" ] || {
-    echo "Error: FOAM_EXT_LIBBIN not set"
+    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
 }
 
 set -x
 
-# update OpenFOAM version strings if required
+# Update OpenFOAM version strings if required
 wmakePrintBuild -check || /bin/rm -f OpenFOAM/Make/*/global.? 2>/dev/null
 
 wmakeLnInclude OpenFOAM
 wmakeLnInclude OSspecific/${WM_OSTYPE:-POSIX}
-Pstream/Allwmake $*
+Pstream/Allwmake $targetType $*
 
 OSspecific/${WM_OSTYPE:-POSIX}/Allwmake $*
-wmake $makeType OpenFOAM
+wmake $targetType OpenFOAM
 
-wmake $makeType fileFormats
-wmake $makeType surfMesh
-wmake $makeType triSurface
-wmake $makeType meshTools
-wmake $makeType edgeMesh
+wmake $targetType fileFormats
+wmake $targetType surfMesh
+wmake $targetType triSurface
+wmake $targetType meshTools
+wmake $targetType edgeMesh
 
 # Decomposition methods needed by dummyThirdParty
+# (dummy metisDecomp, scotchDecomp etc) needed by e.g. meshTools
 parallel/decompose/AllwmakeLnInclude
-# dummyThirdParty (dummy metisDecomp, scotchDecomp etc) needed by e.g. meshTools
-dummyThirdParty/Allwmake $*
+dummyThirdParty/Allwmake $targetType $*
 
-wmake $makeType finiteVolume
-wmake $makeType lagrangian/basic
-wmake $makeType lagrangian/distributionModels
-wmake $makeType genericPatchFields
+wmake $targetType finiteVolume
+wmake $targetType lagrangian/basic
+wmake $targetType lagrangian/distributionModels
+wmake $targetType genericPatchFields
 
-# Build the proper scotchDecomp, metisDecomp etc.
-parallel/Allwmake $*
+wmake $targetType conversion
+wmake $targetType sampling
+wmake $targetType mesh/extrudeModel
+wmake $targetType dynamicMesh
+wmake $targetType dynamicFvMesh
+wmake $targetType topoChangerFvMesh
 
-renumber/Allwmake $*
+# Compile scotchDecomp, metisDecomp etc.
+parallel/Allwmake $targetType $*
 
-wmake $makeType conversion
+wmake $targetType ODE
+wmake $targetType randomProcesses
 
-wmake $makeType sampling
+transportModels/Allwmake $targetType $*
+thermophysicalModels/Allwmake $targetType $*
+turbulenceModels/Allwmake $targetType $*
+TurbulenceModels/Allwmake $targetType $*
+wmake $targetType combustionModels
+regionModels/Allwmake $targetType $*
+lagrangian/Allwmake $targetType $*
+mesh/Allwmake $targetType $*
+renumber/Allwmake $targetType $*
+fvAgglomerationMethods/Allwmake $targetType $*
 
-wmake $makeType mesh/extrudeModel
+wmake $targetType fvMotionSolver
+wmake $targetType engine
+wmake $targetType fvOptions
+wmake $targetType regionCoupled
 
-wmake $makeType dynamicMesh
-wmake $makeType dynamicFvMesh
-wmake $makeType topoChangerFvMesh
+postProcessing/Allwmake $targetType $*
 
-wmake $makeType ODE
-wmake $makeType randomProcesses
+wmake $targetType sixDoFRigidBodyMotion
 
-thermophysicalModels/Allwmake $*
-transportModels/Allwmake $*
-turbulenceModels/Allwmake $*
-TurbulenceModels/Allwmake $*
-wmake $makeType combustionModels
-regionModels/Allwmake $*
-lagrangian/Allwmake $*
-mesh/Allwmake $*
-
-fvAgglomerationMethods/Allwmake $*
-
-wmake $makeType fvMotionSolver
-wmake $makeType engine
-
-wmake $makeType fvOptions
-
-wmake $makeType regionCoupled
-
-postProcessing/Allwmake $*
-
-wmake $makeType sixDoFRigidBodyMotion
 
 # ----------------------------------------------------------------- end-of-file
diff --git a/src/fvAgglomerationMethods/Allwmake b/src/fvAgglomerationMethods/Allwmake
--- a/src/fvAgglomerationMethods/Allwmake
+++ b/src/fvAgglomerationMethods/Allwmake
@@ -1,33 +1,36 @@
 #!/bin/sh
-cd ${0%/*} || exit 1    # run from this directory
-makeType=${1:-libso}
+cd ${0%/*} || exit 1    # Run from this directory
+
+# Parse arguments for library compilation
+targetType=libso
+. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
 set -x
 
 export ParMGridGen=$WM_THIRD_PARTY_DIR/ParMGridGen-1.0
 
 if [ -e "$FOAM_LIBBIN/libMGridGen.so" ]
 then
-    wmake $makeType MGridGenGamgAgglomeration
+    wmake $targetType MGridGenGamgAgglomeration
 fi
 
-wmake $makeType pairPatchAgglomeration
+wmake $targetType pairPatchAgglomeration
 
 
 ## get SCOTCH_VERSION, SCOTCH_ARCH_PATH
-#if settings=`$WM_PROJECT_DIR/bin/foamEtcFile config/scotch.sh`
-#then
-#    . $settings
-#    echo "using SCOTCH_ARCH_PATH=$SCOTCH_ARCH_PATH"
-#else
-#    echo
-#    echo "Error: no config/scotch.sh settings"
-#    echo
-#fi
-#
-#if [ -n "$SCOTCH_ARCH_PATH" ]
-#then
-#    wmake $makeType scotchGamgAgglomeration
-#fi
+if settings=`$WM_PROJECT_DIR/bin/foamEtcFile config/scotch.sh`
+then
+    . $settings
+    echo "using SCOTCH_ARCH_PATH=$SCOTCH_ARCH_PATH"
+else
+    echo
+    echo "Error: no config/scotch.sh settings"
+    echo
+fi
+
+if [ -n "$SCOTCH_ARCH_PATH" ]
+then
+    wmake $targetType scotchGamgAgglomeration
+fi
 
 
 # ----------------------------------------------------------------- end-of-file
diff --git a/wmake/src/makeParserCode b/wmake/src/makeParserCode
--- a/wmake/src/makeParserCode
+++ b/wmake/src/makeParserCode
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2011-2014 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 # License
@@ -29,24 +29,25 @@
 #     Use coco-cpp to create parser code
 #
 #------------------------------------------------------------------------------
-cd ${0%/*} || exit 1    # run from this directory
+cd ${0%/*} || exit 1    # Run from this directory
 
+Script=${0##*/}
 
-bindir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER/coco-cpp/bin
-frames=$bindir/../share/coco-cpp
+binDir=$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER/coco-cpp/bin
+frames=$binDir/../share/coco-cpp
 
-[ -d "$bindir" -a -x "$bindir/coco-cpp" ] || {
-    echo "no coco-cpp binary found"
+[ -d "$binDir" -a -x "$binDir/coco-cpp" ] || {
+    echo "$Script error: no coco-cpp binary found"
     exit 1
 }
 
 [ -d "$frames" -a -f "$frames/Parser.frame" -a -f "$frames/Scanner.frame" ] || {
-    echo "no coco-cpp frames found"
+    echo "$Script error: no coco-cpp frames found"
     exit 1
 }
 
-# run coco-cpp:
-$bindir/coco-cpp wmkdependParser.atg
+# Run coco-cpp:
+$binDir/coco-cpp wmkdependParser.atg
 
 echo
 echo Done
diff --git a/wmake/wcleanLnIncludeAll b/wmake/wcleanLnIncludeAll
--- a/wmake/wcleanLnIncludeAll
+++ b/wmake/wcleanLnIncludeAll
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2011-2014 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
 # License
@@ -29,14 +29,15 @@
 #     Delete all the lnInclude directories in the tree.
 #
 #------------------------------------------------------------------------------
+Script=${0##*/}
 
-# default is pwd
+# Default to the CWD
 if [ "$#" -eq 0 ]
 then
     set -- .
 elif [ "$1" = "-h" -o "$1" = "-help" ]
 then
-    echo "Usage: ${0##*/} [dir1] .. [dirN]"
+    echo "Usage: $Script [dir1] .. [dirN]"
     echo
     echo "    Delete all the lnInclude directories in the tree"
     echo
@@ -44,15 +45,23 @@ then
 fi
 
 
-for i
+for dir
 do
-    if [ -d "$i" ]
+    if [ -d "$dir" ]
     then
-        echo "removing lnInclude directories: $i"
-        find $i -depth -type d -name lnInclude -exec rm -rf {} \;
+        echo "removing lnInclude directories: $dir"
+        find $dir -depth -type d -name lnInclude -exec rm -rf {} \;
     else
-        echo "no directory: $i" 1>&2
+        echo "no directory: $dir" 1>&2
     fi
 done
+
+
+#------------------------------------------------------------------------------
+# Cleanup local variables and functions
+#------------------------------------------------------------------------------
+
+unset Script
+
 
 #------------------------------------------------------------------------------
diff --git a/wmake/wmake b/wmake/wmake
--- a/wmake/wmake
+++ b/wmake/wmake
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2011-2013 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2011-2014 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
 # License
@@ -26,7 +26,27 @@
 #     wmake
 #
 # Description
-#     General, easy to use make system for multi-platform development.
+#     General, easy to use make system for multi-platform development
+#     with support for local and network parallel compilation.
+#
+#     This updated wmake supports out-of-tree object and dependency files to
+#     avoid the clutter which accumulates in the source-tree with the original
+#     wmake system.  Now when building the OpenFOAM package both the object and
+#     dependency files are now located in a tree with the same structure as the
+#     source tree but in the platforms/$WM_OPTIONS sub-directory of
+#     $WM_PROJECT_DIR.
+#
+#     When building user libraries and applications which are not located in the
+#     OpenFOAM source-tree the object and dependency files are located in a tree
+#     with the same structure as the source tree but in the Make/$WM_OPTIONS
+#     sub-directory.
+#
+#     The disadvantage of the out-of-tree compilation is that the dependency
+#     files are harder to find but are sometimes useful to study which header
+#     files are included.  For those who need access to the dependency files the
+#     new wdep script is provided to locate them.
+#     See the wdep script header or run:
+#         wdep -h
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
@@ -40,32 +60,41 @@ Usage: $Script [OPTION] [dir]
        $Script [OPTION] target [dir [MakeDir]]
 
 options:
-  -s | -silent      invoke make in 'silent' mode (do not echo commands)
-  -help             print the usage
+  -s | -silent      Run make in 'silent' mode (do not echo commands)
+  -a | -all         Run wmake in all subdirectories
+  -h | -help        Print the usage
 
 
 A general, easy-to-use make system for multi-platform development
+with support for local and network parallel compilation.
 
 The 'target' is a Makefile target:
-  e.g., Make/linux64GccDPOpt/fvMesh.o
+  e.g., platforms/linux64GccDPOpt/.../fvMesh.o
 
 or a special target:
-  all               all subdirectories, uses any Allwmake files if they exist
-  exe               build statically linked executable
-  lib               build statically linked archive lib (.a)
-  libo              build statically linked lib (.o)
-  libso             build dynamically linked lib (.so)
-  jar               build Java jar
-  dep               build lnInclude and dependencies only
+  all               wmake all subdirectories, running Allwmake files if present
+  exe               Compile statically linked executable
+  lib               Compile statically linked archive lib (.a)
+  libo              Compile statically linked lib (.o)
+  libso             Compile dynamically linked lib (.so)
+  dep               Compile lnInclude and dependencies only
 
 USAGE
     exit 1
 }
 
-# normally use "make"
+
+# Default make is the "make" in the path
 make="make"
 
-# parse options
+
+#------------------------------------------------------------------------------
+# Parse arguments and options
+#------------------------------------------------------------------------------
+
+# Default to compiling the local target only
+all=
+
 while [ "$#" -gt 0 ]
 do
     case "$1" in
@@ -74,6 +103,10 @@ do
         ;;
     -s | -silent)
         make="$make -s"
+        shift
+        ;;
+    -a | -all | all)
+        all="all"
         shift
         ;;
     -*)
@@ -90,30 +123,31 @@ done
 # Check environment variables
 #------------------------------------------------------------------------------
 
-for check in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
+for envar in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
 do
-    eval test "\$$check" || {
-        echo "$Script error: environment variable \$$check not set" 1>&2
+    eval test "\$$envar" || {
+        echo "$Script error: environment variable \$$envar not set" 1>&2
         exit 1
     }
 done
 
 
-# when compiling anything but a standalone exe:
-# WM_PROJECT and WM_PROJECT_DIR must be set
+# When compiling anything but a standalone exe WM_PROJECT and WM_PROJECT_DIR
+# must be set
 [ "$1" = exe -o \( "$WM_PROJECT" -a "$WM_PROJECT_DIR" \) ] || {
     echo "$Script error:" 1>&2
-    echo "    environment variable \$WM_PROJECT or \$WM_PROJECT_DIR not set" 1>&2
+    echo "    environment variable \$WM_PROJECT or " \
+         "\$WM_PROJECT_DIR not set" 1>&2
     echo "    while building project library" 1>&2
     exit 1
 }
 
 
 #------------------------------------------------------------------------------
-# Select the version of make use
+# Setup parallel compilation
 #------------------------------------------------------------------------------
 
-# set WM_NCOMPPROCS automatically when both WM_HOSTS and WM_SCHEDULER are set
+# Set WM_NCOMPPROCS automatically when both WM_HOSTS and WM_SCHEDULER are set
 if [ -z "$WM_NCOMPPROCS" -a -n "$WM_HOSTS" -a -n "$WM_SCHEDULER" ]
 then
     WM_NCOMPPROCS=$(wmakeScheduler -count)
@@ -142,7 +176,7 @@ fi
 # Check arguments and change to the directory in which to run wmake
 #------------------------------------------------------------------------------
 
-unset dir makeType
+unset dir targetType
 MakeDir=Make
 
 if [ $# -ge 1 ]
@@ -151,13 +185,13 @@ then
     then
         dir=$1
     else
-        makeType=$1
+        targetType=$1
     fi
 
-    # specified directory name:
+    # Specified directory name:
     [ $# -ge 2 ] && dir=$2
 
-    # specified alternative name for the Make sub-directory:
+    # Specified alternative name for the Make sub-directory:
     [ $# -ge 3 ] && MakeDir=$3
 
     if [ "$dir" ]
@@ -171,55 +205,71 @@ fi
 
 
 #------------------------------------------------------------------------------
-# Recurse the application directories tree
+# Recurse the source tree to compile "all" targets
 #------------------------------------------------------------------------------
 
-if [ "$makeType" = all ]
+if [ "$all" = "all" ]
 then
     if [ -e Allwmake ]
     then
         ./Allwmake
         exit $?
-    elif [ ! -d $MakeDir ]
-    then
-        # FOAM_APPS=$(find . -maxdepth 1 \( -type d -a ! -name "." -a ! -name Optional -a ! -name Make \)  -printf "%f ")
-        # avoid 'find' with '-printf' ... not entirely portable
-        FOAM_APPS=$(for d in *; do [ -d "$d" -a "$d" != Optional -a "$d" != Make ] && echo "$d"; done | xargs)
-        $make -k -f $WM_DIR/MakefileApps FOAM_APPS="$FOAM_APPS"
-        exit $?
+    else
+        # Find all the sub-directories containing a 'Make' directory
+        FOAM_APPS=$(\
+                       for d in *; \
+                       do [ -d "$d" -a "$d" != Optional -a "$d" != Make ] \
+                          && echo "$d"; \
+                       done | xargs \
+                 )
+        if [ ! "$FOAM_APPS" = "" ]
+        then
+            # Compile all applications in sub-directories
+            $make ${WM_CONTINUE_ON_ERROR:+-k} \
+                  -f $WM_DIR/MakefileApps \
+                  TARGET="$targetType" FOAM_APPS="$FOAM_APPS"
+        fi
+        # If the current directory contains a 'Make' directory continue
+        # otherwise exit
+        if [ ! -d $MakeDir ]
+        then
+            exit $?
+        fi
     fi
 fi
 
 
 #------------------------------------------------------------------------------
-# Search up directories tree for the Make sub-directory and build there
-# Also check the existance of the 'files' file
+# Search up the directory tree for the Make sub-directory,
+# check the existance of the 'files' file and build there if present
 #------------------------------------------------------------------------------
 
 unset dir
-MakeDir=Make
 
-expandpath()
+expandPath()
 {
-    dir=`dirname $1`
+    dir=$(dirname $1)
     cwd=$PWD
     cd $dir
     exPath=$PWD
     cd $cwd
 }
 
-find_target()
+findTarget()
 {
-    expandpath $1
+    expandPath $1
 
-    if [ "$exPath" = "$WM_PROJECT_DIR" -o "$exPath" = "$HOME" -o "$exPath" = "/" ]
+    if [ "$exPath" = "$WM_PROJECT_DIR" \
+                   -o "$exPath" = "$HOME" \
+                   -o "$exPath" = "/" \
+       ]
     then
-        echo "$Script error: could not find Make directory"
+        echo "$Script error: could not find Make directory" 1>&2
     elif [ -d "$1/Make" ]; then
         echo "    Found target directory " $1
         dir=$1
     else
-        find_target "$1/.."
+        findTarget "$1/.."
     fi
 }
 
@@ -228,8 +278,8 @@ then
     echo "$Script: '$MakeDir' directory does not exist in $PWD" 1>&2
     echo "    Searching up directories tree for Make directory"
 
-    find_target .
-    makeType=
+    findTarget .
+    targetType=
 
     if [ "$dir" ]
     then
@@ -251,14 +301,14 @@ fi
 # Transform options
 #------------------------------------------------------------------------------
 
-# transform "all" or no option to "libso" if that looks appropriate or remove it
+# Transform no option to "libso" if that looks appropriate or remove it
 # so that the call to make builds the application
-if [ "$makeType" = all -o "$makeType" = "" ]
+if [ "$targetType" = "" ]
 then
-    unset makeType
+    unset targetType
     if grep -e '^ *LIB *=' "$MakeDir/files" >/dev/null 2>&1
     then
-        makeType=libso
+        targetType=libso
     fi
 fi
 
@@ -268,23 +318,33 @@ fi
 # files and options being built in parallel
 #------------------------------------------------------------------------------
 
+objectsDir=$MakeDir/$WM_OPTIONS
+if echo $PWD | grep "$WM_PROJECT_DIR"
+then
+    platformPath=$WM_PROJECT_DIR/platforms/${WM_OPTIONS}
+    objectsDir=$platformPath$(echo $PWD | sed s%$WM_PROJECT_DIR%% )
+fi
+
 (
-    cd $MakeDir
     unset MAKEFLAGS
-    make -s -f $WM_DIR/MakefileOptions
-    make -s -f $WM_DIR/MakefileFiles allFiles
+    mkdir -p $objectsDir
+
+    # Pre-build the $WM_OPTIONS/options file
+    # which is included when building the $WM_OPTIONS/files file
+    $make -s -f $WM_DIR/MakefileFiles MAKE_DIR=$MakeDir OBJECTS_DIR=$objectsDir\
+          $objectsDir/options
+
+    $make -s -f $WM_DIR/MakefileFiles MAKE_DIR=$MakeDir OBJECTS_DIR=$objectsDir
 )
 
 
 #------------------------------------------------------------------------------
-# Check the $OBJECTS_DIR = $MakeDir/$WM_OPTIONS/objectFiles file
-# was created successfully
+# Check the $objectsDir/sourceFiles file was created successfully
 #------------------------------------------------------------------------------
 
-OBJECTS_DIR=$MakeDir/$WM_OPTIONS
-
-[ -r $OBJECTS_DIR/objectFiles ] || {
-    echo "$Script error: file '$OBJECTS_DIR/objectFiles' could not be created in $PWD" 1>&2
+[ -r $objectsDir/sourceFiles ] || {
+    echo "$Script error: file '$objectsDir/sourceFiles'" \
+         "could not be created in $PWD" 1>&2
     exit 1
 }
 
@@ -293,29 +353,32 @@ OBJECTS_DIR=$MakeDir/$WM_OPTIONS
 # Make the dependency files
 #------------------------------------------------------------------------------
 
-touch $OBJECTS_DIR/dontIncludeDeps
-
-case "$makeType" in
-lib | libo | libso | dep )
-    $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps lnInclude/uptodate
-    ;;
+# For libraries create lnInclude ...
+case "$targetType" in
+    lib | libo | libso | dep )
+        # ... but only if 'LIB' is declared in 'Make/files'
+        if grep -e '^ *LIB *=' "$MakeDir/files" >/dev/null 2>&1
+        then
+            $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir \
+                  OBJECTS_DIR=$objectsDir lnInclude
+        fi
+        ;;
 esac
 
-$make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps $OBJECTS_DIR/dependencies
 
-rc=$?
-[ $rc -eq 0 ] || exit $rc
+#------------------------------------------------------------------------------
+# Make the dependency files or object files and link
+#------------------------------------------------------------------------------
+
+exec $make -f $WM_DIR/Makefile MAKE_DIR=$MakeDir OBJECTS_DIR=$objectsDir \
+     $targetType
 
 
 #------------------------------------------------------------------------------
-# Make the object files and link
+# Cleanup local variables and functions
 #------------------------------------------------------------------------------
 
-if [ "$makeType" != dep ]
-then
-    cmd="$make -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/includeDeps $makeType"
-    # echo "cmd=$cmd"
-    exec $cmd
-fi
+unset Script usage expandPath findTarget
+
 
 #------------------------------------------------------------------------------
diff --git a/wmake/wmakeCheckPwd b/wmake/wmakeCheckPwd
--- a/wmake/wmakeCheckPwd
+++ b/wmake/wmakeCheckPwd
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
+#   \\  /    A nd           | Copyright (C) 2011-2014 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
 # License
@@ -23,13 +23,14 @@
 #     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Script
-#     wmakeCheckPwd
+#     wmakeCheckPwd <dir>
 #
 # Description
-#     Check that the current working directory is equal to a particular
-#     target directory, resolving the absolute path as required
+#     Check that the current working directory is the directory <dir>
 #
 #-------------------------------------------------------------------------------
+Script=${0##*/}
+
 unset quietOpt
 
 usage() {
@@ -38,13 +39,12 @@ usage() {
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
     cat<<USAGE
 
-usage: ${0##*/} [OPTION] dirName
+Usage: $Script [OPTION] dirName
 
 options:
   -q | -quiet   suppress all normal output
 
-  Check that the current working directory is equal to a particular
-  target directory, resolving the absolute path as required
+  Check that the current working directory is the directory <dir>
 
   Exit status 0 when the directories are identical
   Exit status 1 on error
@@ -54,7 +54,10 @@ USAGE
 }
 
 
-# parse options
+#------------------------------------------------------------------------------
+# Parse arguments and options
+#------------------------------------------------------------------------------
+
 while [ "$#" -gt 0 ]
 do
     case "$1" in
@@ -76,27 +79,40 @@ done
 
 
 [ "$#" -eq 1 ] || usage
+
+# Set dirName to <dir>
 dirName="$1"
 
-
-# trivial checks first
+# Simple check against $PWD
 [ "$PWD" = "$dirName" ] && exit 0
 
+# Check existance of <dir>
 [ -d "$dirName" ] || {
-    [ "$quietOpt" = true ] || echo "Error: Directory does not exist $dirName"
+    [ "$quietOpt" = true ] || {
+        echo "$Script error: Directory does not exist $dirName"
+    }
     exit 1
 }
 
-
-# use /bin/pwd to get the absolute path (could be linked)
+# Use /bin/pwd to get the absolute path (could be linked)
 thisDir=$(/bin/pwd)
 target=$(cd $dirName 2>/dev/null && /bin/pwd)
 
-# okay
+# Return 0 if this directory is <dir>
 [ "$thisDir" = "$target" ] && exit 0
 
-# some other error
-[ "$quietOpt" = true ] || echo "Error: Current directory is not $dirName"
+# This directory is not <dir>
+[ "$quietOpt" = true ] || {
+    echo "$Script error: Current directory is not $dirName"
+}
 exit 1
+
+
+#------------------------------------------------------------------------------
+# Cleanup local variables and functions
+#------------------------------------------------------------------------------
+
+unset Script usage
+
 
 #------------------------------------------------------------------------------
