wmake: Improve messages from wclean, wrmdep and wmakeLnIncludeAll

diff --git a/wmake/wrmdep b/wmake/wrmdep
--- a/wmake/wrmdep
+++ b/wmake/wrmdep
@@ -163,15 +163,17 @@ oldFolders)
     # Default is the current directory
     [ "$#" -gt 0 ] || set -- .
 
+    echo "Removing dep files that refer to sources files that no longer exist..."
+
     for checkDir
     do
         findObjectDir $checkDir
 
         if [ -d $objectsDir ]
         then
-            echo "Searching: $objectsDir"
+            echo "    searching: $objectsDir"
         else
-            echo "Skipping non-dir: $objectsDir"
+            echo "    skipping non-dir: $objectsDir"
             continue
         fi
 
@@ -182,7 +184,7 @@ oldFolders)
             # Check C++ or Flex source file exists
             if [ ! -r "$sourceFile" ];
             then
-                echo "rm $depFile"
+                echo "    rm $depFile"
                 rm -f $depFile 2>/dev/null
             fi
         done
@@ -192,20 +194,23 @@ oldFolders)
 
 updateMode)
 
-    [ "$PWD" = "$WM_PROJECT_DIR" ] \
-        || usage "Not in the project top-level directory"
+    if [ "$PWD" != "$WM_PROJECT_DIR" ]
+    then
+        echo "Cannot 'update', not in the project top-level directory"
+        exit 1
+    fi
 
-    echo "Purging all dep files that relate to files that no longer exist..."
+    echo "Removing dep files corresponding to source files that no longer exist..."
     fileNameList=$(find -L src applications -name '*.[CHL]' -type l)
 
     for filePathAndName in $fileNameList
     do
         fileName=$(basename $filePathAndName)
-        echo "Purging from 'src': $fileName"
+        echo "    'src': $fileName"
         cd src
         $Script -a $fileName
 
-        echo "Purging from 'applications': $fileName"
+        echo "    'applications': $fileName"
         cd ../applications
         $Script -a $fileName
 
