paraFoam: Use CMake to locate the installations of ParaView and VTK
This should make the configuration more platform independent

Resolves bug report https://bugs.openfoam.org/view.php?id=4407

diff --git a/etc/config.csh/paraview b/etc/config.csh/paraview
--- a/etc/config.csh/paraview
+++ b/etc/config.csh/paraview
@@ -46,65 +46,24 @@ endif
 unset cmakeDir
 
 # Set up the paraview environment
-switch ("$ParaView_TYPE")
+switch ( "$ParaView_TYPE" )
 case none:
-
-    unset PV_PLUGIN_PATH
     breaksw
 
 case system:
 
-    # Look for a paraview installation
-    set pvserverExe=`which pvdataserver`
+    which pvdataserver > /dev/null
     if ( $status == 0 ) then
-        set paraviewBinDir=`dirname $pvserverExe`
-        set paraviewBinDir=`cd $paraviewBinDir && pwd -P`
-    endif
-
-    # Set the environment
-    if ( $?paraviewBinDir ) then
-    if ( -d "$paraviewBinDir" ) then
-        setenv ParaView_DIR `dirname $paraviewBinDir`
-
+        # Determine the version
         setenv ParaView_VERSION `unset LD_LIBRARY_PATH && \
-                                 $pvserverExe --version | \
+                                 pvdataserver --version | \
                                  awk '{print $NF}'`
         setenv ParaView_MAJOR `echo $ParaView_VERSION | sed 's/\.[^\.]\+$//g'`
-
-        # Set the ParaView installation
-        setenv ParaView_LIB_DIR `unset LD_LIBRARY_PATH && ldd $pvserverExe | \
-                                 grep -o "/[^ ]\+/libvtk.*-pv$ParaView_MAJOR\.so[^ ]*" | \
-                                 head -n 1 | xargs dirname`
-        setenv ParaView_INCLUDE_DIR $ParaView_DIR/include/paraview-$ParaView_MAJOR
-
-        # Set the VTK installation, if it is not bundled inside ParaView
-        if ( ! -f $ParaView_INCLUDE_DIR/vtkMultiBlockDataSetAlgorithm.h ) then
-            set libvtkCommonCore=`unset LD_LIBRARY_PATH && ldd $pvserverExe | \
-                                  grep -o "/[^ \t]\+libvtkCommonCore[^ \t]\+" | \
-                                  xargs readlink -f`
-            setenv VTK_LIB_DIR `dirname $libvtkCommonCore`
-            setenv VTK_INCLUDE_DIR $ParaView_DIR/include/vtk-`echo $libvtkCommonCore | \
-                                                              sed 's/.*\.so\.//g'`
-            unset libvtkCommonCore
-        else
-            setenv VTK_LIB_DIR $ParaView_LIB_DIR
-            setenv VTK_INCLUDE_DIR $ParaView_INCLUDE_DIR
-        endif
-
-        # Add to the library paths
-        setenv LD_LIBRARY_PATH ${ParaView_LIB_DIR}:${LD_LIBRARY_PATH}
-        if ( "$ParaView_LIB_DIR" != "$VTK_LIB_DIR" ) then
-            setenv LD_LIBRARY_PATH ${VTK_LIB_DIR}:${LD_LIBRARY_PATH}
-        fi
 
         # Set the plugin directory
         setenv PV_PLUGIN_PATH $FOAM_LIBBIN/paraview-$ParaView_MAJOR
         setenv LD_LIBRARY_PATH ${PV_PLUGIN_PATH}:${LD_LIBRARY_PATH}
     endif
-    endif
-
-    unset pvserverExe paraviewBinDir vtkMajor vtkLibDir vtkIncludeDir
-    breaksw
 
 case paraviewopenfoam:
 
@@ -117,17 +76,12 @@ case paraviewopenfoam:
     # Set the environment
     if ( $?paraviewDir ) then
     if ( -d "$paraviewDir" ) then
-        setenv ParaView_DIR $paraviewDir
-        setenv ParaView_LIB_DIR `echo "$ParaView_DIR"/lib* | tr ' ' ':'`
-        setenv ParaView_INCLUDE_DIR $ParaView_DIR/include/paraview-$ParaView_MAJOR
+        # Add to the path
+        setenv PATH $paraviewDir/bin:${PATH}
+
+        # Set the plugin directory
         setenv PV_PLUGIN_PATH $FOAM_LIBBIN/paraview-$ParaView_MAJOR
-
-        setenv VTK_LIB_DIR $ParaView_LIB_DIR
-        setenv VTK_INCLUDE_DIR $ParaView_INCLUDE_DIR
-
-        # Add to the path and the library path
-        setenv PATH $ParaView_DIR/bin:${PATH}
-        setenv LD_LIBRARY_PATH ${ParaView_LIB_DIR}:${PV_PLUGIN_PATH}:${LD_LIBRARY_PATH}
+        setenv LD_LIBRARY_PATH ${PV_PLUGIN_PATH}:${LD_LIBRARY_PATH}
     endif
     endif
 
@@ -146,28 +100,28 @@ case ThirdParty:
 
     # Set the environment
     if ( -d "$paraviewDir" ) then
-        setenv ParaView_DIR $paraviewDir
-        setenv ParaView_LIB_DIR `echo "$ParaView_DIR"/lib* | tr ' ' ':'`
-        setenv ParaView_VERSION `echo $ParaView_DIR | sed 's/.*ParaView-//g'`
+
+        # Determine the version
+        setenv ParaView_VERSION `echo $paraviewDir | sed 's/.*ParaView-//g'`
         setenv ParaView_MAJOR `echo $ParaView_VERSION | sed 's/\.[^\.]\+$//g'`
-        setenv ParaView_INCLUDE_DIR $ParaView_DIR/include/paraview-$ParaView_MAJOR
+
+        # Add to the path
+        setenv PATH $paraviewDir/bin:${PATH}
+
+        # Set the plugin directory
         setenv PV_PLUGIN_PATH $FOAM_LIBBIN/paraview-$ParaView_MAJOR
-
-        setenv VTK_LIB_DIR $ParaView_LIB_DIR
-        setenv VTK_INCLUDE_DIR $ParaView_INCLUDE_DIR
-
-        # Add to the path and the library path
-        setenv PATH $ParaView_DIR/bin:${PATH}
-        setenv LD_LIBRARY_PATH ${ParaView_LIB_DIR}:${PV_PLUGIN_PATH}:${LD_LIBRARY_PATH}
+        setenv LD_LIBRARY_PATH ${PV_PLUGIN_PATH}:${LD_LIBRARY_PATH}
 
         # Add in python libraries if required
-        set paraviewPython=$ParaView_DIR/Utilities/VTKPythonWrapping
+        set paraviewPython=$paraviewDir/Utilities/VTKPythonWrapping
         if ( -r $paraviewPython ) then
+            setenv paraviewLibDir `echo "$paraviewDir"/lib* | tr ' ' ':'`
             if ( $?PYTHONPATH ) then
-                setenv PYTHONPATH $PYTHONPATH:$paraviewPython:$ParaView_LIB_DIR
+                setenv PYTHONPATH $PYTHONPATH:$paraviewPython:$paraviewLibDir
             else
-                setenv PYTHONPATH $paraviewPython:$ParaView_LIB_DIR
+                setenv PYTHONPATH $paraviewPython:$paraviewLibDir
             endif
+            unset paraviewLibDir
         endif
         unset paraviewPython
     endif
@@ -178,18 +132,20 @@ case ThirdParty:
 endsw
 
 # Report
-if ( $?ParaView_DIR ) then
-if ( -d "$ParaView_DIR" && $?FOAM_VERBOSE && $?prompt ) then
-    echo "Using paraview"
-    echo "    ParaView_DIR         : $ParaView_DIR"
-    echo "    ParaView_LIB_DIR     : $ParaView_LIB_DIR"
-    echo "    ParaView_INCLUDE_DIR : $ParaView_INCLUDE_DIR"
-    if ( $ParaView_TYPE == system ) then
-        echo "    VTK_LIB_DIR          : $VTK_LIB_DIR"
-        echo "    VTK_INCLUDE_DIR      : $VTK_INCLUDE_DIR"
+if ( $?FOAM_VERBOSE && $?prompt && "$ParaView_TYPE" != "none" ) then
+    if ( ! $?PV_PLUGIN_PATH ) then
+        echo "Warning: ParaView not found"
+    else
+        which pvdataserver > /dev/null
+        if ( $status == 0 ) then
+            echo "Using ParaView: `which paraview`"
+        else
+            echo "Using ParaView"
+        endif
+        echo "    ParaView_VERSION = $ParaView_VERSION"
+        echo "    ParaView_MAJOR = $ParaView_MAJOR"
+        echo "    PV_PLUGIN_PATH = $PV_PLUGIN_PATH"
     endif
-    echo "    PV_PLUGIN_PATH       : $PV_PLUGIN_PATH"
-endif
 endif
 
 unset cleaned
