tutorials: Consistency of All* scripts
Various minor changes to tutorial scripts. In particular, ensuring that
they all change to the containing directory so that batches of tutorials
can be run easily from the root of the installation.

diff --git a/tutorials/fluid/helmholtzResonance/Allrun b/tutorials/fluid/helmholtzResonance/Allrun
--- a/tutorials/fluid/helmholtzResonance/Allrun
+++ b/tutorials/fluid/helmholtzResonance/Allrun
@@ -1,7 +1,7 @@
 #!/bin/sh
+cd ${0%/*} || exit 1    # Run from this directory
 
-cd ${0%/*} || exit 1
-
+# Source tutorial run functions
 . $WM_PROJECT_DIR/bin/tools/RunFunctions
 
 # Run function links the appropriate mesh files and clones the case
@@ -30,6 +30,12 @@ run resolved
 # Run with the plenum modelled by a boundary condition
 run modelled
 
+if ! which gnuplot > /dev/null 2>&1
+then
+    echo "gnuplot not found - skipping graph creation" >&2
+    exit 1
+fi
+
 # Plot a comparison of the pressure in the neck
 cat << EOF | gnuplot -persist
 
@@ -45,3 +51,5 @@ plot \
     "modelled/postProcessing/probes/0/p" us 1:(\$4-1e5) t "Modelled Plenum" w l
 
 EOF
+
+#------------------------------------------------------------------------------
diff --git a/tutorials/multiphaseEuler/hydrofoil/validation/createGraph b/tutorials/multiphaseEuler/hydrofoil/validation/createGraph
--- a/tutorials/multiphaseEuler/hydrofoil/validation/createGraph
+++ b/tutorials/multiphaseEuler/hydrofoil/validation/createGraph
@@ -2,7 +2,7 @@
 
 if ! which gnuplot > /dev/null 2>&1
 then
-    echo 'gnuplot not found - skipping graph creation' >&2
+    echo "gnuplot not found - skipping graph creation" >&2
     exit 1
 fi
 
@@ -45,4 +45,3 @@ plot [0:1] \
 EOF
 
 #------------------------------------------------------------------------------
-
